---
- hosts: ubuntuos
  become: yes
  tasks: 
  - name: install git
    apt:
      namee: git
      state: present
    ignore_errors: yes

  - name: install tree
    apt:
      name: tree
      state: present
    ignore_errors: yes
  
  - name: install wget
    apt:
      name: wget
      state: present
    ignore_errors: yes